AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  IAMUserName:
    Description: Enter the name for the IAM user that will be created for the Seqera Platform
    Type: String
    Default: SeqeraPlatform
  RoleName:
    Description: Enter the name for the IAM role that will be assumed by the Seqera Platform IAM user
    Type: String
    Default: SeqeraPlatformRole
  S3BucketName:
    Description: Enter the name for you S3 bucket
    Type: String
    Default: seqera-platform-data

Resources:
  SeqeraPlatformUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: !Ref IAMUserName
  SeqeraPlatformRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !GetAtt SeqeraPlatformUser.Arn
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Ref SeqeraPlatformForgePolicy
        - !Ref SeqeraPlatformLaunchPolicy
      RoleName: !Ref RoleName
  SeqeraPlatformForgePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: SeqeraPlatformForgePolicy
      Description: Permissions to deploy a new AWS Batch compute environment
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Sid: PlatformForge
            Action:
              - 'ssm:GetParameters'
              - 'iam:CreateInstanceProfile'
              - 'iam:DeleteInstanceProfile'
              - 'iam:GetRole'
              - 'iam:RemoveRoleFromInstanceProfile'
              - 'iam:CreateRole'
              - 'iam:DeleteRole'
              - 'iam:AttachRolePolicy'
              - 'iam:PutRolePolicy'
              - 'iam:AddRoleToInstanceProfile'
              - 'iam:PassRole'
              - 'iam:DetachRolePolicy'
              - 'iam:ListAttachedRolePolicies'
              - 'iam:DeleteRolePolicy'
              - 'iam:ListRolePolicies'
              - 'iam:TagRole'
              - 'iam:TagInstanceProfile'
              - 'batch:CreateComputeEnvironment'
              - 'batch:DescribeComputeEnvironments'
              - 'batch:CreateJobQueue'
              - 'batch:DescribeJobQueues'
              - 'batch:UpdateComputeEnvironment'
              - 'batch:DeleteComputeEnvironment'
              - 'batch:UpdateJobQueue'
              - 'batch:DeleteJobQueue'
              - 'fsx:DeleteFileSystem'
              - 'fsx:DescribeFileSystems'
              - 'fsx:CreateFileSystem'
              - 'fsx:TagResource'
              - 'ec2:DescribeSecurityGroups'
              - 'ec2:DescribeAccountAttributes'
              - 'ec2:DescribeSubnets'
              - 'ec2:DescribeLaunchTemplates'
              - 'ec2:DescribeLaunchTemplateVersions'
              - 'ec2:CreateLaunchTemplate'
              - 'ec2:DeleteLaunchTemplate'
              - 'ec2:DescribeKeyPairs'
              - 'ec2:DescribeVpcs'
              - 'ec2:DescribeInstanceTypeOfferings'
              - 'ec2:GetEbsEncryptionByDefault'
              - 'elasticfilesystem:DescribeMountTargets'
              - 'elasticfilesystem:CreateMountTarget'
              - 'elasticfilesystem:CreateFileSystem'
              - 'elasticfilesystem:DescribeFileSystems'
              - 'elasticfilesystem:DeleteMountTarget'
              - 'elasticfilesystem:DeleteFileSystem'
              - 'elasticfilesystem:UpdateFileSystem'
              - 'elasticfilesystem:PutLifecycleConfiguration'
              - 'elasticfilesystem:TagResource'
            Resource: '*'
  SeqeraPlatformLaunchPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: SeqeraPlatformLaunchPolicy
      Description: Permissions to launch a Pipeline on an AWS Batch compute environment
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Sid: PlatformLaunch
            Action:
              - 's3:Get*'
              - 's3:List*'
              - 'batch:DescribeJobQueues'
              - 'batch:CancelJob'
              - 'batch:SubmitJob'
              - 'batch:ListJobs'
              - 'batch:TagResource'
              - 'batch:DescribeComputeEnvironments'
              - 'batch:TerminateJob'
              - 'batch:DescribeJobs'
              - 'batch:RegisterJobDefinition'
              - 'batch:DescribeJobDefinitions'
              - 'ecs:DescribeTasks'
              - 'ec2:DescribeInstances'
              - 'ec2:DescribeInstanceTypes'
              - 'ec2:DescribeInstanceAttribute'
              - 'ecs:DescribeContainerInstances'
              - 'ec2:DescribeInstanceStatus'
              - 'ec2:DescribeImages'
              - 'logs:Describe*'
              - 'logs:Get*'
              - 'logs:List*'
              - 'logs:StartQuery'
              - 'logs:StopQuery'
              - 'logs:TestMetricFilter'
              - 'logs:FilterLogEvents'
              - 'ses:SendRawEmail'
            Resource: '*'
  SeqeraPlatformAccessKeys:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref SeqeraPlatformUser
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3BucketName

Outputs:
  SeqeraPlatoformUserAccessKeyId:
    Description: The User access key to upload to Seqera Platform as credentials
    Value: !Ref SeqeraPlatformAccessKeys
  SeqeraPlatoformUserSecretAccessKey:
    Description: The User secret access key to upload to Seqera Platform as credentials
    Value: !GetAtt SeqeraPlatformAccessKeys.SecretAccessKey
  SeqeraPlatoformRole:
    Description: The role to be assumed by Seqera Platform to perform AWS actions
    Value: !GetAtt SeqeraPlatformRole.Arn
